apiVersion: apps/v1
kind: Deployment
metadata:
  name: donation-backend
  labels:
    app: donation-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: donation-backend
  template:
    metadata:
      labels:
        app: donation-backend
    spec:
      containers:
      - name: donation-backend
        image: donation-backend:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8084
        env:
        - name: SPRING_DATASOURCE_URL
          value: jdbc:postgresql://postgres-service:5432/donation
        - name: SPRING_DATASOURCE_USERNAME
          value: postgres
        - name: SPRING_DATASOURCE_PASSWORD
          value: postgres
        - name: MANAGEMENT_ENDPOINTS_WEB_EXPOSURE_INCLUDE
          value: "*"
        - name: MANAGEMENT_ENDPOINT_PROMETHEUS_ENABLED
          value: "true"
        - name: EUREKA_CLIENT_ENABLED
          value: "false"
        - name: EUREKA_CLIENT_REGISTER_WITH_EUREKA
          value: "false"
        - name: EUREKA_CLIENT_FETCH_REGISTRY
          value: "false"
---
apiVersion: v1
kind: Service
metadata:
  name: donation-service
spec:
  selector:
    app: donation-backend
  ports:
  - port: 8084
    targetPort: 8084
    nodePort: 30084
  type: NodePort
